'''
Create coco json file
Maps id numbers from coco dataset to the name of the object
'''
import json

def main():
    D = {}
    D[1] = "person"
    D[2] = "bicycle"
    D[3] = "car"
    D[4] = "motorcycle"
    D[5] = "airplane"
    D[6] = "bus"
    D[7] = "train"
    D[8] = "truck"
    D[9] = "boat"
    D[10] = "traffic_light"
    D[11] = "fire_hydrant"
    D[12] = "street_sign"
    D[13] = "stop_sign"
    D[14] = "parking_meter"
    D[15] = "bench"
    D[16] = "bird"
    D[17] = "cat"
    D[18] = "dog"
    D[19] = "horse"
    D[20] = "sheep"
    D[21] = "cow"
    D[22] = "elephant"
    D[23] = "bear"
    D[24] = "zebra"
    D[25] = "giraffe"
    D[26] = "hat"
    D[27] = "backpack"
    D[28] = "umbrella"
    D[29] = "shoe"
    D[30] = "eye_glasses"
    D[31] = "handbag"
    D[32] = "tie"
    D[33] = "suitcase"
    D[34] = "frisbee"
    D[35] = "skis"
    D[36] = "snowboard"
    D[37] = "sports_ball"
    D[38] = "kite"
    D[39] = "baseball_bat"
    D[40] = "baseball_glove"
    D[41] = "skateboard"
    D[42] = "surfboard"
    D[43] = "tennis_racket"
    D[44] = "bottle"
    D[45] = "plate"
    D[46] = "wine_glass"
    D[47] = "cup"
    D[48] = "fork"
    D[49] = "knife"
    D[50] = "spoon"
    D[51] = "bowl"
    D[52] = "banana"
    D[53] = "apple"
    D[54] = "sandwich"
    D[55] = "orange"
    D[56] = "broccoli"
    D[57] = "carrot"
    D[58] = "hot_dog"
    D[59] = "pizza"
    D[60] = "donut"
    D[61] = "cake"
    D[62] = "chair"
    D[63] = "couch"
    D[64] = "potted_plant"
    D[65] = "bed"
    D[66] = "mirror"
    D[67] = "dining_table"
    D[68] = "window"
    D[69] = "desk"
    D[70] = "toilet"
    D[71] = "door"
    D[72] = "tv"
    D[73] = "laptop"
    D[74] = "mouse"
    D[75] = "remote"
    D[76] = "keyboard"
    D[77] = "cell_phone"
    D[78] = "microwave"
    D[79] = "oven"
    D[80] = "toaster"
    D[81] = "sink"
    D[82] = "refrigerator"
    D[83] = "blender"
    D[84] = "book"
    D[85] = "clock"
    D[86] = "vase"
    D[87] = "scissors"
    D[88] = "teddy_bear"
    D[89] = "hair_drier"
    D[90] = "toothbrush"
    D[91] = "hair_brush"
    with open('coco.json', 'w') as fp:
        json.dump(D,fp)

main()
